# The workflow to create
name: Create release PR
on:
  workflow_dispatch:
    inputs:
      release_version:
        description: "Release version '0.1.2' (without 'v')"
        required: true
      snapshot_version:
        description: "Snapshot version '0.2.0-SNAPSHOT' (without 'v')"
        required: true

jobs:
  create_release_pr:
    name: Create release PR (job)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: 0
      - name: Create release branch
        uses: peterjgrainger/action-create-branch@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: release-${{ github.event.inputs.release_version }}
      - name: Checkout release branch
        uses: actions/checkout@v2
        with:
          ref: release-${{ github.event.inputs.release_version }}
      - name: Change release version
        run: sed -i -e "s/^version=.\+$/version=${{ github.event.inputs.release_version }}/g" gradle.properties
      - name: Commit release version
        uses: EndBug/add-and-commit@v4
        with:
          author_name: GitHub Actions
          author_email: action@github.com
          message: Release version ${{ github.event.inputs.release_version }}
          add: '.'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Change snapshot version
        run: sed -i -e "s/^version=.\+$/version=${{ github.event.inputs.snapshot_version }}/g" gradle.properties
      - name: Commit snapshot version
        uses: EndBug/add-and-commit@v4
        with:
          author_name: GitHub Actions
          author_email: action@github.com
          message: Bump version to ${{ github.event.inputs.snapshot_version }}
          add: '.'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: Release version ${{ github.event.inputs.release_version }}
          branch: release-${{ github.event.inputs.release_version }}
#          delete-branch: true
          draft: true
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
