name: Release (new)
on:
  workflow_dispatch:
    inputs:
      release_version:
        description: "Release version '0.1.2' (without 'v')"
        required: true
      snapshot_version:
        description: "Snapshot version '0.2.0-SNAPSHOT' (without 'v')"
        required: true

jobs:
  release:
    name: Release (job)
    runs-on: ubuntu-latest
    steps:
      - name: Check versions
        run: |
          echo "Checking release version..."
          if echo ${{ github.event.inputs.release_version }} | grep --invert-match '^[0-9]\+\.[0-9]\+\.[0-9]\+$' > /dev/null; then
            echo "Release version is invalid"
            exit 1
          fi

          echo "Checking snapshot version..."
          if echo ${{ github.event.inputs.snapshot_version }} | grep --invert-match '^[0-9]\+\.[0-9]\+\.[0-9]\+-SNAPSHOT$' > /dev/null; then
            echo "Snapshot version is invalid"
            exit 1
          fi

      - name: Setup JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11

      - name: Setup Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Checkout master
        uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: 0

      - name: Create release commits and tag
        run: |
          sed -i -e "s/^version=.\+$/version=${{ github.event.inputs.release_version }}/g" gradle.properties
          git add gradle.properties
          git commit -m "Release version ${{ github.event.inputs.release_version }}"

          git tag -a "v${{ env.version }}" -m "Release version ${{ env.version }}"

          sed -i -e "s/^version=.\+$/version=${{ github.event.inputs.snapshot_version }}/g" gradle.properties
          git add gradle.properties
          git commit -m "Bump version to ${{ github.event.inputs.snapshot_version }}"

          git push origin "v${{ env.version }}"
