name: Create release

on:
  workflow_dispatch:
    inputs:
      commit_hash:
        description: "Hash of 'Release version x.y.z' commit"
        required: true

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.commit_hash }}

      - name: Check commit title and extract version
        run: |
          export commit_title=$(git log --pretty=format:%s -1 ${{ github.event.inputs.commit_hash }})
          echo "Commit title: $commit_title"
          if [[ $commit_title =~ ^Release\ version\ [0-9]*\.[0-9]*\.[0-9]*$ ]]; then
            echo "Valid commit title"
          else
            echo "Invalid commit title"
            exit 1
          fi
          export version=$(echo ${commit_title} | sed s/^Release\ version\ //g)
          echo "Will use version ${version}"
          echo "version=${version}" >> $GITHUB_ENV

      - name: Create release draft
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: "v${{ env.version }}"
          release_name: "v${{ env.version }}"
          body: |
            *Fill in*
          draft: true
          prerelease: false

      - name: Test
        run: |
          echo "${{ env.version }}"

